### PR TITLE
add  plugin L7-MapLibre

### PR DESCRIPTION
**Pull request by lzxue**

### CODE REVIEW

**Comment by HarelM** [comment]
The docs are referenecing mapbox and in one example I looked I couldn't find a reference to maplibre.
Is this library actually using maplibre?

**Comment by lzxue** [comment]
> The docs are referenecing mapbox and in one example I looked I couldn't find a reference to maplibre. Is this library actually using maplibre?

the docs not update ,you  can see this demo https://l7.antv.antgroup.com/examples/map/map/#maplibre

the source code https://github.com/antvis/L7/blob/master/packages/maps/src/maplibre/map.ts

```tsx
import { Scene, PointLayer } from '@antv/l7';
import { MapLibre } from '@antv/l7-maps';
const scene = new Scene({
    id: 'map',
    map: new MapLibre({
      zoom: 10,
      style: "https://api.maptiler.com/maps/streets/style.json?key=YbCPLULzWdf1NplssEIc", // style URL
      minZoom: 0,
      maxZoom: 18
    })
  });

```

**Comment by HarelM** [comment]
Please update the docs then and I'll be happy to merge this PR.

**Comment by lzxue** [comment]
> Please update the docs then and I'll be happy to merge this PR.

ok

**Pull request merged**
