### PR TITLE
Add mapgrab

### PR DESCRIPTION
**Pull request by marucjmar**

### CODE REVIEW

**Comment by meenaxc** [comment]
Hi @marucjmar, meena here. Would you like to join the slack developer community? 
auto-invite via https://slack.openstreetmap.us/

**Comment by marucjmar** [comment]
@meenaxc Thanks for the invite, I’ve joined! 😊

**Comment by HarelM** [comment]
Sorry @marucjmar, since this is a paid software and is not open source, we do not feel this would be the right place to add it.

**Comment by marucjmar** [comment]
@HarelM Initially, it was a paid solution, but after some thought, I decided to make it available to the community for free. I even [updated the documentation](https://github.com/MapGrab/mapgrab.github.io/commit/be5ace04c03c26d0b93a8adf310eb001ad2d691b). All the necessary libraries are published in the official NPM repository.

**Comment by HarelM** [comment]
Thanks for the update @marucjmar!
Great to see how you help the community by open sourcing this!
Would be great to see more of your contribution to the core library and other wrappers!

**Pull request merged**
